name: NetworkClient
version: 1.0
main: org.mcservernetwork.client.Client
api-version: 1.13
commands:
  network:
    aliases: [sectors, networkinfo, networkoverview, netinf, sinfo, serverstatus,
              sectorlist, status, sectorstatus sectorinfo]
    description: "Opens a sector status panel"
