name: Master CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build -x copyJar
  release:
    runs-on: [ubuntu-latest]
    needs: [build]
    steps:
    - name: Make files accessible
      run: |
        chmod +x ./NetworkClient/build/libs/NetworkClient-1.0.jar
        chmod +x ./NetworkProxy/build/libs/NetworkProxy-1.0.jar
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Release Build"
        files: "*.jar"
    
